#!/bin/bash

# This script is used to backup rootfs to a btrfs subvolume by creating a new snapshot and send to nas
# The snapshot is created by the following steps:
# 1. mount rootfs
# 2. create snapshot
# 3. send snapshot to nas
# 3.1 every month create a full backup
# 3.2 every day create an incremental backup
# 4. delete old snapshots
# 5. unmount rootfs

# mount rootfs
root_mountpoint="/mnt"
snapshot_dir="${root_mountpoint}/.snapshots"
root_device="$(df / | sed '1d' | awk '{print $NR}')"

mount_rootfs() {
	sudo mount "${root_device}" "${root_mountpoint}"
}

# TODO(Drogon): check mounted, cut /proc/mounts | awk
# if [ "$(df | grep "${root_mountpoint}" | wc -l)" -eq 0 ]; then
# 	echo "rootfs is not mounted"
# 	exit 1
# fi

# create snapshot
subvol="ubuntu"
datetime="$(date +'%Y%m%d%H%M')"
snapshot_name="${snapshot_dir}/${subvol}-${datetime}"
create_snapshot() {
	vol="${root_mountpoint}/@${subvol}"
	echo "backup rootfs ${vol} to ${snapshot_name}"
	sudo btrfs subvolume snapshot -r "${vol}" "${snapshot_name}"
}

# send snapshot to nas
send_incremental_snapshot_to_nas() {
	echo "send incremental snapshot to nas"

	snapshot_subvol=".snapshots/${subvol}"
	parent_snapshot="$(sudo btrfs subvolume list /mnt | grep ${snapshot_subvol} | awk '{print $NF}' | sort | tail -2 | head -1)"
	full_parent_snapshot_path="${root_mountpoint}/${parent_snapshot}"
	# remote_incremental_path format is /mnt/data/Data/Backup/CM/RootFS/btrfs/incremental_${subvol}_${parent_snapshot_date}-${datetime}.img
	parent_snapshot_date="$(echo "${parent_snapshot}" | awk -F '-' '{print $NF}')"
	remote_incremental_path="/mnt/data/Data/Backup/CM/RootFS/btrfs/incremental_${subvol}_${parent_snapshot_date}-${datetime}.img"
	echo "sudo btrfs send -p ${full_parent_snapshot_path} ${snapshot_name} | ssh drogon@nas.local 'cat > ${remote_incremental_path}'"
	sudo btrfs send -p ${full_parent_snapshot_path} ${snapshot_name} | ssh drogon@nas.local "cat > ${remote_incremental_path}"
}

send_full_snapshot_to_nas() {
	echo "send full snapshot to nas"

	# sudo btrfs send /mnt/.snapshots/ubuntu-202310091057 | ssh drogon@nas.local 'cat > /mnt/data/Data/Backup/CM/RootFS/btrfs/snapshot_ubuntu_202310091057.img'
	remote_full_path="/mnt/data/Data/Backup/CM/RootFS/btrfs/snapshot_${subvol}_${datetime}.img"
	echo "sudo btrfs send ${snapshot_name} | ssh drogon@nas.local 'cat > ${remote_full_path}'"
	sudo btrfs send ${snapshot_name} | ssh drogon@nas.local "cat > ${remote_full_path}"
}

send_snapshot_to_nas() {
	local force="$1"
	if [ "${force}" = "true" ]; then
		echo "force send full snapshot to nas"
		send_full_snapshot_to_nas
		return
	fi

	# every month create a full backup
	# every day create an incremental backup
	# list all snapshot, sort by date, get the latest one
	# if prev month, send full snapshot
	# else send incremental snapshot
	# if only one snapshot exists, send full snapshot
	if [ "$(ls -ad /mnt/.snapshots/ubuntu* | wc -l)" -eq 1 ]; then
		send_full_snapshot_to_nas
	elif [ "$(ls -ad /mnt/.snapshots/ubuntu* | sort -r | awk 'NR==2 {print $NF}' | awk -F '-' '{print $NF}' | cut -c 5-6)" != "$(date +'%m')" ]; then
		# NR == 2, get the second latest snapshot, NR == 1 is the latest snapshot(created by this script)
		send_full_snapshot_to_nas
	else
		send_incremental_snapshot_to_nas
	fi
}

# delete old snapshots
delete_old_snapshots() {
	# delete old snapshots
	# keep 3 snapshots
	# ls -ad /mnt/.snapshots/ubuntu* | sort -r | awk 'NR>3 {print $NF}' | xargs -I{} sudo btrfs subvolume delete {}
	sudo btrfs subvolume list /mnt | grep '.snapshots/ubuntu' | awk '{print $NF}' | sort -r | tail -n +4 | xargs -I{} sudo btrfs subvolume delete -c -v "${root_mountpoint}/{}"
}

umount_rootfs() {
	sudo umount "${root_mountpoint}"
}

# Add flag if flag '-f' is passed, mean do full snapshot
# Add flag if flag '--only-create-snapshot' is passed, mean only do create snapshot, don't send to nas
usage() {
	echo "Usage: $0 [-h] [-f] [--only-create-snapshot]"
	echo "Options:"
	echo "  -h: show this help message"
	echo "  -f: force to create full snapshot"
	echo "  --only-create-snapshot: only create snapshot, don't send to nas"
}

main() {
	local force=false
	local only_create_snapshot=false

	case "$1" in
	-h)
		usage
		return
		;;
	-f)
		force=true
		shift
		;;
	--only-create-snapshot)
		only_create_snapshot=true
		shift
		;;
	*) ;;
	esac

	mount_rootfs
	create_snapshot
	if [ "${only_create_snapshot}" = false ]; then
		sleep 3 # for commit
		send_snapshot_to_nas "${force}"
		delete_old_snapshots
	fi
	umount_rootfs

}

main "$*"
